# Generated by Django 4.2.1 on 2023-05-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLogReaderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_time', models.CharField(max_length=155, verbose_name='Час')),
                ('etv_id', models.IntegerField(verbose_name='ID события')),
                ('computer_name', models.CharField(max_length=155, verbose_name='Имя компьютера')),
                ('user_name', models.CharField(max_length=155, verbose_name='Имя пользователя')),
                ('category', models.CharField(max_length=155, verbose_name='Категория Логгов')),
                ('source', models.CharField(max_length=155, verbose_name='Источник')),
                ('record', models.CharField(max_length=155, verbose_name='Рекорд')),
                ('event_type', models.CharField(max_length=155, verbose_name='Тип события')),
                ('message', models.CharField(max_length=155, verbose_name='Сообщение')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
